# -- Site Configuration --
# Refer to the theme docs for more details about each of these parameters.
# https://blowfish.page/docs/getting-started/

theme = "blowfish"
baseURL = "https://adlnc.ovh/"
defaultContentLanguage = "en"
publishDir = "../public"
# contentDir = "./content/en"



# pluralizeListTitles = "true" # hugo function useful for non-english languages, find out more in  https://gohugo.io/getting-started/configuration/#pluralizelisttitles

enableRobotsTXT = true
paginate = 20
summaryLength = 30

buildDrafts = false
buildFuture = false

timeZone = "Europe/Paris"

googleAnalytics = "G-T7N29W2RFB"

[imaging]
  anchor = 'Center'

[taxonomies]
  tag = "tags"
  category = "categories"
  author = "authors"
  series = "series"

[permalinks]
  post = "/:slug/"

[sitemap]
  changefreq = 'daily'
  filename = 'sitemap.xml'
  priority = 0.5

[outputs]
  home = ["HTML", "RSS", "JSON"]
